/*
 *  ICTK - Internet Chess ToolKit
 *  More information is available at http://ictk.sourceforge.net
 *  Copyright (C) 2002 J. Varsoke <jvarsoke@ghostmanonfirst.com>
 *  All rights reserved.
 *
 *  $Id: FICSBlockMode.java,v 1.1 2003/04/10 20:46:06 jvarsoke Exp $
 *
 *  This file is part of ICTK.
 *
 *  ICTK is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  ICTK is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with ICTK; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package ictk.boardgame.chess.net.ics.fics;

public interface FICSBlockMode {
   public static final int BLOCK_START             = 21,
                           BLOCK_SEPARATOR         = 22,
                           BLOCK_END               = 23,
                           BLOCK_POSE_START        = 24,
                           BLOCK_POSE_END          = 25,

                           BLK_NULL                = 0,
                           BLK_GAME_MOVE           = 1,
                           BLK_ABORT               = 10,
                           BLK_ACCEPT              = 11,
                           BLK_ADDLIST             = 12,
                           BLK_ADJOURN             = 13,
                           BLK_ALLOBSERVERS        = 14,
                           BLK_ASSESS              = 15,
                           BLK_BACKWARD            = 16,
                           BLK_BELL                = 17,
                           BLK_BEST                = 18,
                           BLK_BNAME               = 19,
                           BLK_BOARDS              = 20,
                           BLK_BSETUP              = 21,
                           BLK_BUGWHO              = 22,
                           BLK_CBEST               = 23,
                           BLK_CLEARMESSAGES       = 24,
                           BLK_CLRSQUARE           = 25,
                           BLK_CONVERT_BCF         = 26,
                           BLK_CONVERT_ELO         = 27,
                           BLK_CONVERT_USCF        = 28,
                           BLK_COPYGAME            = 29,
                           BLK_CRANK               = 30,
                           BLK_CSHOUT              = 31,
                           BLK_DATE                = 32,
                           BLK_DECLINE             = 33,
                           BLK_DRAW                = 34,
                           BLK_ECO                 = 35,
                           BLK_EXAMINE             = 36,
                           BLK_FINGER              = 37,
                           BLK_FLAG                = 38,
                           BLK_FLIP                = 39,
                           BLK_FMESSAGE            = 40,
                           BLK_FOLLOW              = 41,
                           BLK_FORWARD             = 42,
                           BLK_GAMES               = 43,
                           BLK_GETGI               = 44,
                           BLK_GETPI               = 45,
                           BLK_GINFO               = 46,
                           BLK_GOBOARD             = 47,
                           BLK_HANDLES             = 48,
                           BLK_HBEST               = 49,
                           BLK_HELP                = 50,
                           BLK_HISTORY             = 51,
                           BLK_HRANK               = 52,
                           BLK_INCHANNEL           = 53,
                           BLK_INDEX               = 54, //"obsolete"
                           BLK_INFO                = 55,
                           BLK_ISET                = 56,
                           BLK_IT                  = 57,
                           BLK_IVARIABLES          = 58,
                           BLK_JKILL               = 59,
                           BLK_JOURNAL             = 60,
                           BLK_JSAVE               = 61,
                           BLK_KIBITZ              = 62,
                           BLK_LIMITS              = 63,
                           BLK_LINE                = 64,//"not on FICS"
                           BLK_LLOGONS             = 65,
                           BLK_LOGONS              = 66,
                           BLK_MAILHELP            = 67,
                           BLK_MAILMESS            = 68,
                           BLK_MAILMOVES           = 69,
                           BLK_MAILOLDMOVES        = 70,//"obsolete"
                           BLK_MAILSOURCE          = 71,
                           BLK_MAILSTORED          = 72,
                           BLK_MATCH               = 73,
                           BLK_MESSAGES            = 74,
                           BLK_MEXAMINE            = 75,
                           BLK_MORETIME            = 76,
                           BLK_MOVES               = 77,
                           BLK_NEWS                = 78,
                           BLK_NEXT                = 79,
                           BLK_OBSERVE             = 80,
                           BLK_OLDMOVES            = 81,
                           BLK_OLDSTORED           = 82,
                           BLK_OPEN                = 83,
                           BLK_PARTNER             = 84,
                           BLK_PASSWORD            = 85,
                           BLK_PAUSE               = 86,
                           BLK_PENDING             = 87,
                           BLK_PFOLLOW             = 88,
                           BLK_POBSERVE            = 89,
                           BLK_PREFRESH            = 90,
                           BLK_PRIMARY             = 91,
                           BLK_PROMOTE             = 92,
                           BLK_PSTAT               = 93,
                           BLK_PTELL               = 94,
                           BLK_PTIME               = 95,
                           BLK_QTELL               = 96,
                           BLK_QUIT                = 97,
                           BLK_RANK                = 98,
                           BLK_RCOPYGAME           = 99,
                           BLK_RFOLLOW             = 100,
                           BLK_REFRESH             = 101,
                           BLK_REMATCH             = 102,
                           BLK_RESIGN              = 103,
                           BLK_RESUME              = 104,
                           BLK_REVERT              = 105,
                           BLK_ROBSERVE            = 106,
                           BLK_SAY                 = 107,
                           BLK_SERVERS             = 108,//"Not on FICS"
                           BLK_SET                 = 109,
                           BLK_SHOUT               = 110,
                           BLK_SHOWLIST            = 111,
                           BLK_SIMABORT            = 112,
                           BLK_SIMALLABORT         = 113,
                           BLK_SIMADJOURN          = 114,
                           BLK_SIMALLADJOURN       = 115,
                           BLK_SIMGAMES            = 116,
                           BLK_SIMMATCH            = 117,
                           BLK_SIMNEXT             = 118,
                           BLK_SIMOBSERVE          = 119,
                           BLK_SIMOPEN             = 120,
                           BLK_SIMPASS             = 121, //"Obsolete"
                           BLK_SIMPREV             = 122,
                           BLK_SMOVES              = 123,
                           BLK_SMPOSITION          = 124,
                           BLK_SPOSITION           = 125,
                           BLK_STATISTICS          = 126,
                           BLK_STORED              = 127,
                           BLK_STYLE               = 128,
                           BLK_SUBLIST             = 129,
                           BLK_SWITCH              = 130,
                           BLK_TAKEBACK            = 131,
                           BLK_TELL                = 132,
                           BLK_TIME                = 133,
                           BLK_TOMOVE              = 134,
                           BLK_TOURNSET            = 135,
                           BLK_UNALIAS             = 136,
                           BLK_UNEXAMINE           = 137,
                           BLK_UNOBSERVE           = 138,
                           BLK_UNPAUSE             = 139,
                           BLK_UPTIME              = 140,
                           BLK_USCF                = 141,//"obsolete"
                           BLK_USTAT               = 142,
                           BLK_VARIABLES           = 143,
                           BLK_WHENSHUT            = 144,
                           BLK_WHISPER             = 145,
                           BLK_WHO                 = 146,
                           BLK_WITHDRAW            = 147,
                           BLK_WNAME               = 148,
                           BLK_XKIBITZ             = 149,
                           BLK_XTELL               = 150,
                           BLK_XWHISPER            = 151,
                           BLK_ZNOTIFY             = 152,
                           BLK_REPLY               = 153,//"not on fics"
                           BLK_SUMMON              = 154,
                           BLK_SEEK                = 155,
                           BLK_UNSEEK              = 156,
                           BLK_SOUGHT              = 157,
                           BLK_PLAY                = 158,
                           BLK_ALIAS               = 159,
                           BLK_NEWBIES             = 160,
                           BLK_SR                  = 161,
                           BLK_CA                  = 162,
                           BLK_TM                  = 163,
                           BLK_GETGAME             = 164,
                           BLK_CCNEWSE             = 165,
                           BLK_CCNEWSF             = 166,
                           BLK_CCNEWSI             = 167,
                           BLK_CCNEWSP             = 168,
                           BLK_CCNEWST             = 169,
                           BLK_CSNEWSE             = 170,
                           BLK_CSNEWSF             = 171,
                           BLK_CSNEWSI             = 172,
                           BLK_CSNEWSP             = 173,
                           BLK_CSNEWST             = 174,
                           BLK_CTNEWSE             = 175,
                           BLK_CTNEWSF             = 176,
                           BLK_CTNEWSI             = 177,
                           BLK_CTNEWSP             = 178,
                           BLK_CTNEWST             = 179,
                           BLK_CNEWS               = 180,
                           BLK_SNEWS               = 181,
                           BLK_TNEWS               = 182,
                           BLK_RMATCH              = 183,
                           BLK_RSTAT               = 184,
                           BLK_CRSTAT              = 185,
                           BLK_HRSTAT              = 186,
                           BLK_GSTAT               = 187,
                           BLK_OLDPSTAT            = 188,
                           BLK_HSTAT               = 189,
                           BLK_PING                = 190,
                           BLK_EVENT               = 191,
                           BLK_ENDEVENT            = 192,
                           BLK_BOARDINFO           = 193,
                           BLK_AUDIOCHAT           = 194,
                           BLK_SHOWADMINS          = 195,
                           BLK_COMMIT              = 196,
                           BLK_TRUNCATE            = 197,
                           BLK_SHOWSRS             = 198,
                           BLK_CRASH               = 1, //1 is already assigned

                           BLK_ADDCOMMENT          = 300,
                           BLK_ADDPLAYER           = 301,
                           BLK_ADJUDICATE          = 302,
                           BLK_AHELP               = 303,
                           BLK_ADMIN               = 304,
                           BLK_ANEWS               = 305,
                           BLK_ANNOUNCE            = 306,
                           BLK_ANNUNREG            = 307,
                           BLK_ASETCLOCK           = 308,
                           BLK_ASETV               = 309,
                           BLK_ASETADMIN           = 310,
                           BLK_ASETBLITZ           = 311,
                           BLK_ASETBUGHOUSE        = 312,
                           BLK_ASETEMAIL           = 313,
                           BLK_ASETHANDLE          = 314,
                           BLK_ASETLIGHT           = 315,
                           BLK_ASETPASSWD          = 316,
                           BLK_ASETREALNAME        = 317,
                           BLK_ASETSTD             = 318,
                           BLK_ASETSUICIDE         = 319,
                           BLK_ASETWILD            = 320,
                           BLK_CHKFOPEN            = 321,//"obsolete"
                           BLK_CHKIP               = 322,
                           BLK_CHKGAME             = 323,
                           BLK_CHKMALLOC           = 324,//"obsolete"
                           BLK_CHKMALLOC_OLD       = 325,//"obsolete"
                           BLK_CHKPL               = 326,
                           BLK_CHKSC               = 327,
                           BLK_CHKTS               = 328,
                           BLK_CMUZZLE             = 329,//"obsolete"
                           BLK_CNEWSI              = 330,
                           BLK_CNEWSF              = 331,
                           BLK_CANEWSI             = 332,
                           BLK_CANEWSF             = 333,
                           BLK_FTELL               = 334,
                           BLK_HIDEINFO            = 335,
                           BLK_LCHANLIST           = 336,
                           BLK_LISTEXPUNGE         = 337,
                           BLK_MUZZLE              = 338,//"obsolete"
                           BLK_NUKE                = 339,
                           BLK_POSE                = 340,
                           BLK_ASETMAXPLAYER       = 341,
                           BLK_QUOTA               = 342,
                           BLK_RAISEDEAD           = 343,
                           BLK_RATING_RECALC       = 344,//"obsolete"
                           BLK_REMPLAYER           = 345,
                           BLK_RERANK              = 346,//"obsolete"
                           BLK_SHOWCOMMENT         = 347,
                           BLK_SHUTDOWN            = 348,
                           BLK_STOPML              = 349,
                           BLK_CHKDOMAIN           = 350,
                           BLK_CHKEMAIL            = 351,
                           BLK_CHKUSERNAME         = 352,
                           BLK_DUMPUSAGE           = 353,
                           BLK_FIXDB               = 354,
                           BLK_PATHLEN             = 355,
                           BLK_ASETCRAZYHOUSE      = 356,
                           BLK_CNEWSE              = 357,
                           BLK_CNEWSP              = 358,
                           BLK_CNEWST              = 359,
                           BLK_CANEWSE             = 360,
                           BLK_CANEWSP             = 361,
                           BLK_CANEWST             = 362,
                           BLK_LNEWS               = 363,
                           BLK_LTOLERANCE          = 364,
                           BLK_CHECKPASSWORD       = 365,//"Adbar only"
                           BLK_DISCONNECT          = 366,//"Adbar only"
                           BLK_INTERFACE           = 367,
                           BLK_FIXADJOURNED        = 368,
                           BLK_RESETBLITZ          = 369,
                           BLK_RESETSTD            = 370,
                           BLK_RESETLIGHT          = 371,
                           BLK_RESETWILD           = 372,
                           BLK_RESETBUGHOUSE       = 373,
                           BLK_RESETCRAZYHOUSE     = 374,
                           BLK_RESETSUICIDE        = 375,
                           BLK_BESTRESETBLITZ      = 376,
                           BLK_BESTRESETSTD        = 377,
                           BLK_BESTRESETLIGHT      = 378,
                           BLK_BESTRESETWILD       = 379,
                           BLK_BESTRESETBUGHOUSE   = 380,
                           BLK_BESTRESETCRAZYHOUSE = 381,
                           BLK_BESTRESETSUICIDE    = 382,
                           BLK_CHKID               = 383,
                           BLK_ERROR_BADCOMMAND    = 512,
                           BLK_ERROR_BADPARAMS     = 513,
                           BLK_ERROR_AMBIGUOUS     = 514,
                           BLK_ERROR_RIGHTS        = 515,
                           BLK_ERROR_OBSOLETE      = 516,
                           BLK_ERROR_REMOVED       = 517,
                           BLK_ERROR_NOTPLAYING    = 518,
                           BLK_ERROR_NOSEQUENCE    = 519,
                           BLK_ERROR_LENGTH        = 520;

}
